### ISSUE TITLE
Doesn't support one-line if statements

### ISSUE THREAD

**Issue by dhollinger** [Bakudankun/PICO-8.vim#1]
Noticed when I opened a game I've worked on that the syntax highlighting doesn't like the pico8/Lua one-line if statements:

![Screenshot from 2021-06-08 09-23-31](https://user-images.githubusercontent.com/2914211/121202938-4fa87d80-c83b-11eb-8186-55f86d3f0a78.png)

**Comment by Bakudankun** [comment]
Okay, I think I did my best. Please check it out.
