### ISSUE TITLE
Add options

### ISSUE THREAD

**Issue by merwok** [Bakudankun/PICO-8.vim#5]
Options for the plugin itself:
- indent mode (1 space, 2 spaces, 1 tab)
- split mode for terminal output (split, vsplit, new buffer)

Options for running PICO-8: a string to specify options (useful for width/height, -i/-o, etc)

```diff

 function! pico8#run(mods, options) abort
   let cmdline = '"' . pico8#get_config('pico8_path', 'pico8') . '" -run ' . expand('%:p:S')
+  let cmdline = cmdline .. ' ' .. pico8#get_config('pico8_options', '')
```

**Comment by Bakudankun** [comment]
@merwok Very sorry for my late action! I added `pico8_args` option as you suggested!

For other suggestions:
* Indent type and other options should be set by autocommands like `au FileType pico8 setlocal sw=...`, which is far more flexible than adding options to the plugin.
* Split mode can be modified using [`<mods>`](https://vimhelp.org/map.txt.html#%3Cmods%3E) like `:vertical Pico8Run`. You may want to make commands like below.
```vim
command VPico8Run vertical Pico8Run
```

Thank you!
