### ISSUE TITLE
changing colorscheme once file is loaded breaks graphics preview

### ISSUE THREAD

**Issue by Le-Kat** [Bakudankun/PICO-8.vim#6]
when first opening up a .p8 file, the visualization of graphics data works as intended:
![image](https://user-images.githubusercontent.com/37410281/202571808-104fab38-d3ee-4f7d-80ea-e3c685393819.png)

However, if I run alter the colorshceme (whether if be manually or as an autocommand) by running `:colorscheme pico8` this graphics preview breaks:
![image](https://user-images.githubusercontent.com/37410281/202572109-67e3c1c9-1816-4add-97d4-7116afb7234a.png)

So far I've been able to repoduce this only by changing vim's color scheme after a file has been loaded (even if I set it to the same colorscheme that's currently active).

I'm using neovim (v0.8.0), but I can confirm that the same happens when using vim.

**Comment by Bakudankun** [comment]
@Le-Kat 
I added an autocmd to restore colors affter changing colorscheme. I think it fixes this issue.
Thank you for your report!

**Comment by Purple-Tentacle** [comment]
I have the opposite effect. Loading the file does not show the colors. I must run :colorscheme pico8.

**Comment by Bakudankun** [comment]
@Purple-Tentacle Please open a new issue and tell me the detail (e.g. environment, what colorscheme you use and minimal vimrc to reproduce).
